---
header: 
  frame_id: /world_link
id: table_surface
primitives: 
  - 
    type: 1
    dimensions: [1.2, 2.3, 0.09]
primitive_poses: 
  - 
    position: 
      x: 0.171
      y: 0.81
      z: 0.05
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 0
---
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: world_link
id: obstacle
type: 
  key: ''
  db: ''
primitives: 
  - 
    type: 1
    dimensions: [0.3, 0.2, 0.2]
primitive_poses: 
  - 
    position: 
      x: 0.25
      y: 0.25
      z: 0.18
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 0
---
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: world_link
id: cylinder1
type: 
  key: ''
  db: ''
primitives: 
  - 
    type: 3
    dimensions: [0.25, 0.04, 0.0]
primitive_poses: 
  - 
    position: 
      x: 0.0
      y: 0.0
      z: 0.205
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 0